### ISSUE TITLE
After enable R8 full mode getting ParameterizedType error

### ISSUE THREAD

**Issue by proninyaroslav** [skydoves/sandwich#100]
**Please complete the following information:**
- Library Version: 1.3.5
 
**Describe the Bug:**

This issue is similar to the issue in Retrofit (https://github.com/square/retrofit/issues/3751) but I'm not sure, but I've duplicated it here. This happens with AGP 8.0. As a solution, it's proposed to add these proguard lines to the project (https://github.com/square/retrofit/issues/3751#issuecomment-1192043644):
```
 # Keep generic signature of Call, Response (R8 full mode strips signatures from non-kept items). 
 -keep,allowobfuscation,allowshrinking interface retrofit2.Call 
 -keep,allowobfuscation,allowshrinking class retrofit2.Response 
  
 # With R8 full mode generic signatures are stripped for classes that are not 
 # kept. Suspend functions are wrapped in continuations where the type argument 
 # is used. 
 -keep,allowobfuscation,allowshrinking class kotlin.coroutines.Continuation 
```

but it doesn't actually work, After adding this proguard lines I get a slightly different error:
```
 java.lang.IllegalArgumentException: Unable to create call adapter for retrofit2.Call<com.skydoves.sandwich.ApiResponse>
                     for method ComicVineService.issues
                 	at retrofit2.Utils.methodError(SourceFile:47)
                 	at retrofit2.HttpServiceMethod.parseAnnotations(SourceFile:394)
                 	at retrofit2.Retrofit.loadServiceMethod(SourceFile:31)
                 	at retrofit2.Retrofit$1.invoke(SourceFile:45)
                 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                 	at $Proxy9.issues(Unknown Source)
                        ...
Caused by: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
                 	at com.skydoves.sandwich.adapters.ApiResponseCallAdapterFactory.get(SourceFile:53)
                 	at retrofit2.Retrofit.callAdapter(SourceFile:33)
                 	at retrofit2.HttpServiceMethod.parseAnnotations(SourceFile:375)
                 	... 41 more
```

```Kotlin
 @GET("issues?format=$FORMAT&field_list=${Fields.Issues}")
    @JvmSuppressWildcards
    suspend fun issues(
        @Query("api_key") apiKey: String,
        @Query("offset") offset: Int,
        @Query("limit") limit: Int,
        @Query("sort", encoded = true) sort: ComicVineSort?,
        @Query("filter[]", encoded = true) filter: List<ComicVineFilter>?,
    ): ApiResponse<IssuesResponse>
```

**Comment by CarlosEsco** [comment]
I started getting this again with 2.0.0

**Comment by skydoves** [comment]
@CarlosEsco Thanks for reporting this issue. Would you add the proguard rule for now? Let me check out the issue on 2.0.0 soon.

```
# R8 full mode strips signatures from non-kept items.
-keep,allowobfuscation,allowshrinking interface com.skydoves.sandwich.ApiResponse
```

**Comment by ivaniskandar** [comment]
I've had the same issue and I can confirm the rule above works with 2.0.2

**Comment by skydoves** [comment]
@ivaniskandar It would be appreciated if you could check does the rule above works along with 2.0.2.

**Comment by ivaniskandar** [comment]
Yes it works with 2.0.2

**Comment by skydoves** [comment]
@ivaniskandar Thanks for checking it. The new release 2.0.3 contains the proguard rules, and it must work well without add the rules manually.
