### ISSUE TITLE
Why is this error not intercepted

### ISSUE THREAD

**Issue by gugu1993** [skydoves/Sandwich#40]
**Please complete the following information:**
-              sandwich:1.0.4
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
            compileSdkVersion: 30,
            buildToolsVersion: "29.0.3",
**Describe the Bug:**
retrofit2.HttpException: HTTP 400 Response.error()
        at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
        at com.skydoves.sandwich.coroutines.ApiResponseCallDelegate$enqueueImpl$1.onResponse(ApiResponseCallDelegate.kt:33)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
Add a clear description about the problem.

**Expected Behavior:**
net: <-- 400 http://******.com/auth.json (165ms)
net: Server: nginx/1.11.6
net: Date: Fri, 12 Nov 2021 01:20:42 GMT
net: Content-Type: application/json;char
net: Transfer-Encoding: chunked
net: Connection: keep-alive
net: {"code":11015,"message":"无效的客户端"}

**Comment by gugu1993** [comment]
https://github.com/skydoves/Sandwich/issues/5
