### ISSUE TITLE
java.lang.NullPointerException:::sandwich.ApiResponse$Failure$Error.toString

### ISSUE THREAD

**Issue by caosiqiao4000** [skydoves/sandwich#99]
--sandwich 1.3.5
--okhttp 4.10.0
--okio-jvm 3.0.0
--Xiao Mi Note3 (Android 9,API 28)

java.lang.NullPointerException
                 	at okio.Segment.pop(Segment.kt:95)
                 	at okio.Buffer.readString(Buffer.kt:321)
                 	at okio.Buffer.readString(Buffer.kt:302)
                 	at okhttp3.ResponseBody.string(ResponseBody.kt:187)
                 	at com.skydoves.sandwich.ApiResponse$Failure$Error.toString(ApiResponse.kt:82)
                 	at com.skydoves.sandwich.ResponseTransformer__ResponseTransformerKt.message(ResponseTransformer.kt:759)
                 	at com.skydoves.sandwich.ResponseTransformer.message(ResponseTransformer.kt:1)
                 	at com.robertsi.httpresultcope.mapper.ErrorResponseMapper.map(ErrorResponseMapper.kt:37)
                 	at com.robertsi.httpresultcope.mapper.ErrorResponseMapper.map(ErrorResponseMapper.kt:28)
                 	at com.robertsi.httpresultcope.repository.HttpCommonRepository$getManual$1.invokeSuspend(HttpCommonRepository.kt:197)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7db45e5, Dispatchers.IO]
***
Thank you for your open source Sandwich Project
I am currently using and found this error. I hope you can capture and handle this exception

**Comment by skydoves** [comment]
I think this issue is related to OkHttp than this library: https://github.com/square/okhttp/issues/2745

**Comment by caosiqiao4000** [comment]
好是
